### ISSUE TITLE
HistoHour for past year?

### ISSUE THREAD

**Issue by wuntee** [alexanderdavidpan/cryptocompare#6]
Before I start trying to write a recursive API call, I wanted to ask if you knew if cryptocompare (or anywhere for that matter) has the ability to provide raw hourly price data for a long period of time - such as the past year?

I believe the cryptocompare limits to 2000 results.

Thank you.

**Comment by alexanderdavidpan** [comment]
@wuntee You are correct. CryptoCompare's API currently limits the request HistoHour request to 2000 data points. In order to get that data using the cryptocompare gem, you would have to make 5 calls since there are 8760 hours in a year (and 8784 in a leap year). I am closing this because it is an API limitation.
