### ISSUE TITLE
How to get historical price between two different timestamps?

### ISSUE THREAD

**Issue by Rubioli** [alexanderdavidpan/cryptocompare#8]
Hello

First of all Great Gem 👍 

In your example we can do:
`Cryptocompare::PriceHistorical.find('ETH', 'USD', {'ts' => 1452680400})`
To find historical price of cryptocurrency at a given timestamp.

I tried by giving `ts` an array like: `{'ts' => [1452680400, Time.now.to_i]}`, but I get this error:
*{"Response":"Error","Message":"ts param is not an integer, not a valid timestamp.","Type":1,"Aggregated":false,"Data":[]}*

I was wondering if its possible and if so how to get the historical price between two different timestamps?

Thanks in advanced

**Comment by alexanderdavidpan** [comment]
Hi @Rubioli,

Thank you for the compliment.

In order to get the historical price between two different timestamps, you would have to call `Cryptocompare::PriceHistorical.find` two times with different timestamp parameters. This is due to an API limitation in CryptoCompare's API that does not allow for the use case that you have described.
